version: "3.5"

services:
  python:
    build: .
    container_name: python-itw
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
      - 5678:5678
    volumes:
      - .:/app
    depends_on:
      - mongodb
    networks:
      - app-itw
  
  mongodb:
    image: mongo:6.0
    container_name: mongodb-itw
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-itw

  mariadb:
    image: mariadb:10.11
    container_name: mariadb-itw
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - app-itw

  kafka-connect-mongodb:
    image: confluentinc/kafka-connect-mongodb:latest
    container_name: kafka-connect-mongodb
    restart: unless-stopped
    depends_on:
      - kafka
      - mongodb
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: connect-mongodb-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
    volumes:
      - ./connectors/mongodb-sink-connector.json:/etc/kafka-connect-mongodb/mongodb-sink-connector.json
    networks:
      - app-itw

networks:
  app-itw:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
  mariadb-data:
    driver: local
  mariadbdata:
    driver: local
