FROM python:3.9-alpine

RUN apk add --no-cache mariadb-connector-c-dev \
    && apk add --no-cache --virtual .build-deps gcc musl-dev \
    && pip install --no-cache-dir PyMySQL

WORKDIR /app

COPY main.py requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:server", "--host", "0.0.0.0"]


LABEL version="1.0.0"
LABEL description="FastAPI ITW Project"


